
services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306