import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Suspense } from 'react'
import AuthNav from "./components/AuthNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <header className="border-gray-200 border">
          <nav className="bg-gray-50  ">
            <div className="flex flex-wrap justify-between items-center mx-auto max-w-screen-2xl p-4">
              <Link href="/" className="flex items-center space-x-3 rtl:space-x-reverse">
                <svg fill="currentColor" className="bi bi-vector-pen h-6 w-6 flex-no-shrink fill-current" viewBox="0 0 16 16">
                  <path fillRule="evenodd" d="M10.646.646a.5.5 0 0 1 .708 0l4 4a.5.5 0 0 1 0 .708l-1.902 1.902-.829 3.313a1.5 1.5 0 0 1-1.024 1.073L1.254 14.746 4.358 4.4A1.5 1.5 0 0 1 5.43 3.377l3.313-.828zm-1.8 2.908-3.173.793a.5.5 0 0 0-.358.342l-2.57 8.565 8.567-2.57a.5.5 0 0 0 .34-.357l.794-3.174-3.6-3.6z" />
                  <path fillRule="evenodd" d="M2.832 13.228 8 9a1 1 0 1 0-1-1l-4.228 5.168-.026.086z" />
                </svg>
                <span className="self-center text-2xl font-semibold whitespace-nowrap ">E-Uni-Support</span>
              </Link>
              <Suspense fallback={<></>}>
                <AuthNav />
              </Suspense>
            </div>
          </nav>
          <nav className="bg-gray-50 ">
            <div className="max-w-screen-2xl px-4 py-3 mx-auto">
              <div className="flex items-center">
                <ul className="flex flex-row font-medium mt-0 space-x-8 rtl:space-x-reverse text-sm">
                  <li>
                    <Link href="/" className="text-gray-900  hover:underline" aria-current="page">Home</Link>
                  </li>
                  <li>
                    <Link href="/about" className="text-gray-900  hover:underline">About</Link>
                  </li>
                  <li>
                    <Link href="/contact" className="text-gray-900  hover:underline">Contact</Link>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
